/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JFrame;

/**
 *
 * @author Seolargo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        HREditionLabel = new javax.swing.JLabel();
        authorsLabel = new javax.swing.JLabel();
        authorsLabel2 = new javax.swing.JLabel();
        tazminatHesabiButton = new javax.swing.JButton();
        calisanEklemeButton = new javax.swing.JButton();
        projeEklemeButton = new javax.swing.JButton();
        projeBitirmeButton = new javax.swing.JButton();
        projeyeCalisanEklemeButton = new javax.swing.JButton();
        calisanIstenCikarmaButton = new javax.swing.JButton();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        calisaniEkleButton = new javax.swing.JButton();
        calisaniSilButton = new javax.swing.JButton();
        adLabel = new javax.swing.JLabel();
        soyadLabel = new javax.swing.JLabel();
        TCLabel = new javax.swing.JLabel();
        TelefonLabel = new javax.swing.JLabel();
        adresLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        brutMaasLabel = new javax.swing.JLabel();
        calisiyorMuLabel = new javax.swing.JLabel();
        maasProgramiLabel = new javax.swing.JLabel();
        iseGirisTarihiLabel = new javax.swing.JLabel();
        adTextF = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        soyadTextF = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        TCTextF = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        TelefonTextF = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        adresTextF = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        brutMaasTextF = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        titleTextF = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        calisiyorMuTextF = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        maasProgramiTextF = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        iseGirisTarihiTextF = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        ismiTextF = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        ismiLabel = new javax.swing.JLabel();
        yoneticiMaxTextF = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        yoneticiMaxLabel = new javax.swing.JLabel();
        yoneticiMinTextF = new javax.swing.JScrollPane();
        jTextPane13 = new javax.swing.JTextPane();
        yoneticiMinLabel = new javax.swing.JLabel();
        maxCalisanTextF = new javax.swing.JScrollPane();
        jTextPane14 = new javax.swing.JTextPane();
        minCalisanLabel = new javax.swing.JLabel();
        maxCalisanLabel = new javax.swing.JLabel();
        minCalisanTextF = new javax.swing.JScrollPane();
        jTextPane15 = new javax.swing.JTextPane();
        projeEkleButton = new javax.swing.JButton();
        projeSilButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(204, 204, 204));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 10));

        HREditionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HREditionLabel.setForeground(new java.awt.Color(255, 255, 255));
        HREditionLabel.setText("HR Edition");
        sidepane.add(HREditionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        authorsLabel.setForeground(new java.awt.Color(255, 255, 255));
        authorsLabel.setText("Ömer Hamid Kamışlı - Kamil Başkut");
        sidepane.add(authorsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, 30));

        authorsLabel2.setForeground(new java.awt.Color(255, 255, 255));
        authorsLabel2.setText("Emre Çelik - Ömer Faruk Yavuz");
        sidepane.add(authorsLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, 30));

        tazminatHesabiButton.setBackground(new java.awt.Color(85, 65, 118));
        tazminatHesabiButton.setText("Tazminat Hesabı Yapma");
        tazminatHesabiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tazminatHesabiButtonActionPerformed(evt);
            }
        });
        sidepane.add(tazminatHesabiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, 30));

        calisanEklemeButton.setBackground(new java.awt.Color(85, 65, 118));
        calisanEklemeButton.setText("Çalışan Ekleme");
        calisanEklemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanEklemeButtonActionPerformed(evt);
            }
        });
        sidepane.add(calisanEklemeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 30));

        projeEklemeButton.setBackground(new java.awt.Color(85, 65, 118));
        projeEklemeButton.setText("Proje Ekleme");
        projeEklemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projeEklemeButtonActionPerformed(evt);
            }
        });
        sidepane.add(projeEklemeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, 30));

        projeBitirmeButton.setBackground(new java.awt.Color(85, 65, 118));
        projeBitirmeButton.setText("Proje Bitirme");
        projeBitirmeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projeBitirmeButtonActionPerformed(evt);
            }
        });
        sidepane.add(projeBitirmeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 30));

        projeyeCalisanEklemeButton.setBackground(new java.awt.Color(85, 65, 118));
        projeyeCalisanEklemeButton.setText("Projeye Çalışan Ekleme");
        projeyeCalisanEklemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projeyeCalisanEklemeButtonActionPerformed(evt);
            }
        });
        sidepane.add(projeyeCalisanEklemeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 190, 30));

        calisanIstenCikarmaButton.setBackground(new java.awt.Color(85, 65, 118));
        calisanIstenCikarmaButton.setText("Çalışan İşten Çıkarma");
        calisanIstenCikarmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanIstenCikarmaButtonActionPerformed(evt);
            }
        });
        sidepane.add(calisanIstenCikarmaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, 30));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setText("_");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ad", "Soyad", "TC", "Telefon", "Adres", "Title", "Brüt Maaş", "Çalışıyor Mu", "Maaş Programı", "İşe Giriş Tarihi", "İşten Çıkış Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Çalışan Ekleme", jScrollPane2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Adı", "Yönetici Max", "Yönetici Min", "Max Çalışan Sayısı", "Min Çalışan Sayısı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane1.addTab("Proje Ekleme", jScrollPane3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "İsmi", "Yönetici Max", "Yönetici Min", "Max Çalışan Sayısı", "Min Çalışan Sayısı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jTabbedPane1.addTab("Proje Bitirme", jScrollPane4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ad", "Soyad", "TC", "Telefon", "Adres", "Title", "Brüt Maaş", "Çalışıyor Mu", "Maaş Programı", "İşe Giriş Tarihi", "İşten Çıkış Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jTabbedPane1.addTab("Projeye Çalışan Ekleme", jScrollPane5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ad", "Soyad", "TC", "Telefon", "Adres", "Title", "Brüt Maaş", "Çalışıyor Mu", "Maaş Programı", "İşe Giriş Tarihi", "İşten Çıkış Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        jTabbedPane1.addTab("Çalışan İşten Çıkarma", jScrollPane6);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        jTabbedPane1.addTab("Tazminat Hesabı Yapma", jScrollPane7);

        calisaniEkleButton.setText("Çalışanı Ekle");

        calisaniSilButton.setText("Çalışanı Sil");
        calisaniSilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisaniSilButtonActionPerformed(evt);
            }
        });

        adLabel.setText("Ad");

        soyadLabel.setText("Soyad");

        TCLabel.setText("TC");

        TelefonLabel.setText("Telefon");

        adresLabel.setText("Adres");

        titleLabel.setText("Title");

        brutMaasLabel.setText("Brüt Maaş");

        calisiyorMuLabel.setText("Çalışıyor Mu");

        maasProgramiLabel.setText("Maaş Programı");

        iseGirisTarihiLabel.setText("İşe Giriş Tarihi");

        adTextF.setViewportView(jTextPane1);

        soyadTextF.setViewportView(jTextPane2);

        TCTextF.setViewportView(jTextPane3);

        TelefonTextF.setViewportView(jTextPane4);

        adresTextF.setViewportView(jTextPane5);

        brutMaasTextF.setViewportView(jTextPane6);

        titleTextF.setViewportView(jTextPane7);

        calisiyorMuTextF.setViewportView(jTextPane8);

        maasProgramiTextF.setViewportView(jTextPane9);

        iseGirisTarihiTextF.setViewportView(jTextPane10);

        ismiTextF.setViewportView(jTextPane11);

        ismiLabel.setText("İsmi");

        yoneticiMaxTextF.setViewportView(jTextPane12);

        yoneticiMaxLabel.setText("Yönetici Max");

        yoneticiMinTextF.setViewportView(jTextPane13);

        yoneticiMinLabel.setText("Yönetici Min");

        maxCalisanTextF.setViewportView(jTextPane14);

        minCalisanLabel.setText("Min Çalışan");

        maxCalisanLabel.setText("Max Çalışan");

        minCalisanTextF.setViewportView(jTextPane15);

        projeEkleButton.setText("Proje Ekle");
        projeEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projeEkleButtonActionPerformed(evt);
            }
        });

        projeSilButton.setText("Proje Sil");
        projeSilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projeSilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane1)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(calisaniSilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calisaniEkleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adLabel)
                                    .addComponent(soyadLabel)
                                    .addComponent(TCLabel)
                                    .addComponent(TelefonLabel)
                                    .addComponent(brutMaasLabel)
                                    .addComponent(adresLabel)
                                    .addComponent(titleLabel))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maasProgramiLabel)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(calisiyorMuLabel)
                                        .addGap(13, 13, 13))
                                    .addComponent(iseGirisTarihiLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calisiyorMuTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maasProgramiTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iseGirisTarihiTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(soyadTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TCTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TelefonTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(adresTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(174, 174, Short.MAX_VALUE)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yoneticiMaxLabel)
                                            .addComponent(ismiLabel)
                                            .addComponent(yoneticiMinLabel)
                                            .addComponent(maxCalisanLabel)
                                            .addComponent(minCalisanLabel))
                                        .addGap(59, 59, 59)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yoneticiMinTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yoneticiMaxTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ismiTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(minCalisanTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maxCalisanTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(84, 84, 84)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projeEkleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(projeSilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(82, 82, 82))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brutMaasTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin))
                .addGap(72, 72, 72)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adLabel)
                            .addComponent(calisaniEkleButton)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ismiLabel)
                                .addComponent(ismiTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(projeEkleButton)))
                    .addComponent(adTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(soyadLabel)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(calisaniSilButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TCLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TelefonLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maxCalisanLabel)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundLayout.createSequentialGroup()
                                    .addComponent(soyadTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TCTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TelefonTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backgroundLayout.createSequentialGroup()
                                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yoneticiMaxLabel)
                                        .addComponent(yoneticiMaxTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yoneticiMinLabel)
                                        .addComponent(yoneticiMinTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(maxCalisanTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(projeSilButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adresLabel)
                    .addComponent(adresTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minCalisanTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minCalisanLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brutMaasTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brutMaasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(titleTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calisiyorMuLabel)
                    .addComponent(calisiyorMuTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(maasProgramiTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iseGirisTarihiTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iseGirisTarihiLabel)))
                    .addComponent(maasProgramiLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void tazminatHesabiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tazminatHesabiButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_tazminatHesabiButtonActionPerformed

    private void calisanEklemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanEklemeButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_calisanEklemeButtonActionPerformed

    private void projeEklemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projeEklemeButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_projeEklemeButtonActionPerformed

    private void projeBitirmeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projeBitirmeButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_projeBitirmeButtonActionPerformed

    private void projeyeCalisanEklemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projeyeCalisanEklemeButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_projeyeCalisanEklemeButtonActionPerformed

    private void calisanIstenCikarmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanIstenCikarmaButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_calisanIstenCikarmaButtonActionPerformed

    private void calisaniSilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisaniSilButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calisaniSilButtonActionPerformed

    private void projeEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projeEkleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projeEkleButtonActionPerformed

    private void projeSilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projeSilButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projeSilButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HREditionLabel;
    private javax.swing.JLabel TCLabel;
    private javax.swing.JScrollPane TCTextF;
    private javax.swing.JLabel TelefonLabel;
    private javax.swing.JScrollPane TelefonTextF;
    private javax.swing.JLabel adLabel;
    private javax.swing.JScrollPane adTextF;
    private javax.swing.JLabel adresLabel;
    private javax.swing.JScrollPane adresTextF;
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JLabel authorsLabel2;
    private javax.swing.JPanel background;
    private javax.swing.JLabel brutMaasLabel;
    private javax.swing.JScrollPane brutMaasTextF;
    private javax.swing.JButton calisanEklemeButton;
    private javax.swing.JButton calisanIstenCikarmaButton;
    private javax.swing.JButton calisaniEkleButton;
    private javax.swing.JButton calisaniSilButton;
    private javax.swing.JLabel calisiyorMuLabel;
    private javax.swing.JScrollPane calisiyorMuTextF;
    private javax.swing.JLabel iseGirisTarihiLabel;
    private javax.swing.JScrollPane iseGirisTarihiTextF;
    private javax.swing.JLabel ismiLabel;
    private javax.swing.JScrollPane ismiTextF;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane13;
    private javax.swing.JTextPane jTextPane14;
    private javax.swing.JTextPane jTextPane15;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JLabel maasProgramiLabel;
    private javax.swing.JScrollPane maasProgramiTextF;
    private javax.swing.JLabel maxCalisanLabel;
    private javax.swing.JScrollPane maxCalisanTextF;
    private javax.swing.JLabel minCalisanLabel;
    private javax.swing.JScrollPane minCalisanTextF;
    private javax.swing.JButton projeBitirmeButton;
    private javax.swing.JButton projeEkleButton;
    private javax.swing.JButton projeEklemeButton;
    private javax.swing.JButton projeSilButton;
    private javax.swing.JButton projeyeCalisanEklemeButton;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel soyadLabel;
    private javax.swing.JScrollPane soyadTextF;
    private javax.swing.JButton tazminatHesabiButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JScrollPane titleTextF;
    private javax.swing.JLabel yoneticiMaxLabel;
    private javax.swing.JScrollPane yoneticiMaxTextF;
    private javax.swing.JLabel yoneticiMinLabel;
    private javax.swing.JScrollPane yoneticiMinTextF;
    // End of variables declaration//GEN-END:variables
}
