/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import com.mysql.jdbc.PreparedStatement;

/**
 *
 * @author omerhamidkamisli, seolargo
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }
    
    //Author: ÖFY
    //TODO
    //Do not touch the code below!
    /*static ResultSet yap()
    {
    	ResultSet myRs = null;
    	try{
    		Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/employee", "seolargo", "123456");
			Statement myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("select * from employee.employeetable");
    	}
    	catch (Exception e)
    	{
    		e.printStackTrace();
    	}
    	return myRs;
    }*/
    
    //Author: ÖFY
    //Adding data to database.
    static void employeeTableEkle(String sql_sorgu)
    {
    	try
    	{ 		
        	//ResultSet myRs = null;         
            Connection myConn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","seolargo","123456");
            Statement myStat = (Statement) myConn.createStatement();
     		//myRs = myStat.executeQuery("select * from employee.employeetable");
     		/*while(myRs.next())
     		{
     			System.out.println(myRs.getString("name"));
     	 	}*/
        	myStat.executeUpdate(sql_sorgu);        
    	}
    	catch (SQLException e)
    	{
    		e.printStackTrace();
    	}
    }
    
    //Author: ÖFY
    //Adding data to database.
    static void projectTableEkle(String sql_sorgu)
    {
    	try
    	{ 		
        	ResultSet myRs = null;         
            Connection myConn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","seolargo","123456");
            Statement myStat = (Statement) myConn.createStatement();
     		myRs = myStat.executeQuery("select * from employee.projecttable");
        	myStat.executeUpdate(sql_sorgu);        
    	}
    	catch (SQLException e)
    	{
    		e.printStackTrace();
    	}
    }
    
    //Author: ÖFY
    //Updating the data.
    static void updateEmployeeTable(String sql_sorgu)
    {
    	try
    	{  	
    		//Herein the connection is done.
        	Connection myConn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","seolargo","123456");
        	Statement myStat = (Statement) myConn.createStatement();
        	//Herein the execution is done.
        	myStat.executeUpdate(sql_sorgu);        
    	}
    	catch (SQLException e)
    	{
    		e.printStackTrace();
    	}
    }
    
    //Author: ÖFY
    //Updating the data.
    static void updateProjectTable(String sql_sorgu)
    {
    	try
    	{  	
    		//Herein the connection is done.
        	Connection myConn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","seolargo","123456");
        	Statement myStat = (Statement) myConn.createStatement();
        	//Herein the execution is done.
        	myStat.executeUpdate(sql_sorgu);        
    	}
    	catch (SQLException e)
    	{
    		e.printStackTrace();
    	}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_BeginDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_finishDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_title = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cb_salaryType = new javax.swing.JComboBox<>();
        btn_addPersonel = new javax.swing.JButton();
        btn_updatePersonel = new javax.swing.JButton();
        btn_showPersonel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txt_ProjectName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_minManager = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_maxManager = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_minAnalist = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_maxAnalist = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_minDesigner = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_maxDesigner = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_minTester = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_maxTester = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_minProgrammer = new javax.swing.JTextField();
        txt_maxProgrammer = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_projeBegin = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_projeFinish = new javax.swing.JTextField();
        btn_projeEkle = new javax.swing.JButton();
        btn_projeUpdate = new javax.swing.JButton();
        btn_ProjeBitir = new javax.swing.JButton();
        btn_projePersonelGoruntule = new javax.swing.JButton();
        showProjects = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dashboard", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
            		"Name", "Surname", "TC", "Phone", "Address", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txt_name.setName("txt_name"); // NOI18N

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        txt_surname.setName("txt_name"); // NOI18N

        jLabel3.setText("TC");

        txt_tc.setName("txt_name"); // NOI18N

        jLabel4.setText("Telefon");

        txt_phone.setName("txt_name"); // NOI18N

        jLabel5.setText("Adres");

        txt_address.setName("txt_name"); // NOI18N

        jLabel6.setText("Maaş");

        txt_salary.setName("txt_name"); // NOI18N

        jLabel7.setText("İşe Giriş Tarihi");

        txt_BeginDate.setEditable(false);
        txt_BeginDate.setName("txt_name"); // NOI18N

        jLabel8.setText("İşten Ayrılış Tarihi");

        txt_finishDate.setEditable(false);
        txt_finishDate.setName("txt_name"); // NOI18N

        jLabel9.setText("Görev Tanımı");

        cb_title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yönetici", "Analist", "Tasarımcı", "Programcı", "Test" }));

        jLabel10.setText("Maaş Programı");

        cb_salaryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tip 1", "Tip 2", "Tip 3" }));

        btn_addPersonel.setText("Çalışan Ekle");
        
        //Author: ÖFY
        btn_addPersonel.addActionListener((ActionListener) new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				//Declerations here.
				String ad;
				ad = txt_name.getText();
				String soyad;
				soyad = txt_surname.getText();
				String tc;
				tc = txt_tc.getText();
				String phone;
				phone = txt_phone.getText();
				String adres;
				adres = txt_address.getText();
				String salary;
				salary = txt_salary.getText();
				
				/*String beginDate;
				beginDate = txt_BeginDate.getText();
				java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
				java.time.LocalDate textFieldAsDate = java.time.LocalDate.parse(beginDate, formatter);
				
				String finishDate;
				finishDate = txt_finishDate.getText();
				java.time.format.DateTimeFormatter formatter2 = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
				java.time.LocalDate textFieldAsDate2 = java.time.LocalDate.parse(finishDate, formatter2);
				 */
				
				//Herein sql query's are done.
				String sorgu;
				sorgu = "INSERT INTO employee.employeetable (name, surname, TC, phone, address, salary) VALUES (" 
				+ "'" + ad + "'," + "'" + soyad + "'," + "'" + tc + "'," + "'" + phone + "'," + "'" +  adres + "'," + "'" + salary +  "')";
				
				//Printing the console, for debugging purpose.
				System.out.println(sorgu);
				
				//Where server connection happens.
				MainGui.employeeTableEkle(sorgu);
			}
        });
        
        btn_updatePersonel.setText("Çalışan Güncelle");
        
        //Author: ÖFY
        btn_updatePersonel.addActionListener((ActionListener) new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				
				//Declerations here.
				String ad;
				ad = txt_name.getText();
				String soyad;
				soyad = txt_surname.getText();
				String tc;
				tc = txt_tc.getText();
				String phone;
				phone = txt_phone.getText();
				String adres;
				adres = txt_address.getText();
				String salary;
				salary = txt_salary.getText();
				
				//Herein sql query's are done.
				String sql_sorgu = "UPDATE employee.employeetable SET name='" + ad + "', surname='" + soyad + "', tc='" + tc + "', phone='" + phone + 
						"', address='" + adres + "', salary='" + salary + "' WHERE tc="+tc;
				
				//Printing the console, for debugging purpose.
				System.out.println(sql_sorgu);
				
				//Where server connection happens.
				MainGui.updateEmployeeTable(sql_sorgu);
			}
        });
        
        //Author: ÖFY
        //Method shows the list of employees.
        btn_showPersonel.setText("Çalışanları Görüntüle");
        
        btn_showPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showPersonelActionPerformed(evt);
                Connection myConn;
				try {
					myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/employee", "seolargo", "123456");
					java.sql.PreparedStatement ps = myConn.prepareStatement("select * from employee.employeetable");
					ResultSet rs = ps.executeQuery();
					DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
					tm.setRowCount(0);				
					while(rs.next())
					{
						Object o[] = {rs.getString("name"), rs.getString("surname"), rs.getInt("TC"), 
								rs.getInt("phone"), rs.getString("address"), rs.getInt("salary")};
						tm.addRow(o);
					}
					
				} catch (SQLException e1) {
					e1.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_address, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_phone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tc))
                                        .addGap(73, 73, 73)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel7))
                                            .addComponent(txt_BeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_addPersonel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_showPersonel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(349, 349, 349))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_finishDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(btn_updatePersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cb_salaryType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_title, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_salary)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(57, 57, 57)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_BeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_showPersonel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_addPersonel)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_updatePersonel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_finishDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_salaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Personel", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
            		"Project Name", "Yönetici Min", "Analist Min", "Tasarimci Min", "Tester Min", "Yönetici Max", "Analist Max", "Tasarimci Max"
                	, "Tester Max"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel11.setText("Proje Adı");

        jLabel12.setText("Yönetici Min");

        jLabel13.setText("Yönetici Max");

        jLabel14.setText("Analist Min");

        jLabel15.setText("Analist Max");

        jLabel16.setText("Tasarımcı Min");

        jLabel17.setText("Tasarımcı Max");

        jLabel18.setText("Tester Min");

        jLabel19.setText("Tester Max");

        jLabel20.setText("Programcı Min");

        jLabel21.setText("Programcı Max");

        jLabel22.setText("Proje Başlangıç Tarihi");

        txt_projeBegin.setEditable(true);

        jLabel23.setText("Proje Bitiş Tarihi");

        txt_projeFinish.setEditable(true);

        btn_projeEkle.setText("Proje Ekle");
        
        //Author: ÖFY
        btn_projeEkle.addActionListener((ActionListener) new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				
				//Declerations here.
				String projectName;
				projectName = txt_ProjectName.getText();
				
				String yoneticiMin;
				yoneticiMin = txt_minManager.getText();
				String yoneticiMax;
				yoneticiMax = txt_maxManager.getText();					
				
				String analistMin;
				analistMin = txt_minAnalist.getText();
				String analistMax;
				analistMax = txt_maxAnalist.getText();
				
				String tasarimciMin;
				tasarimciMin = txt_minDesigner.getText();		
		  		String tasarimciMax;
				tasarimciMax = txt_maxDesigner.getText();
				
				String testerMin;
				testerMin = txt_minTester.getText();
				String testerMax;
				testerMax = txt_maxTester.getText();
				
				
				/*String beginDate;
				beginDate = txt_BeginDate.getText();
				java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
				java.time.LocalDate textFieldAsDate = java.time.LocalDate.parse(beginDate, formatter);
				
				String finishDate;
				finishDate = txt_finishDate.getText();
				java.time.format.DateTimeFormatter formatter2 = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
				java.time.LocalDate textFieldAsDate2 = java.time.LocalDate.parse(finishDate, formatter2);
				 */
				
				//Herein sql query's are done.
				String sorgu;
				sorgu = "INSERT INTO employee.projecttable (projectName, yoneticiMin, analistMin, tasarimciMin, testerMin, yoneticiMax, analistMax, tasarimciMax, testerMax) "
						+ "VALUES (" + "'" + projectName + "'," + "'" + yoneticiMin + "'," + "'" + analistMin + "'," + "'" 
						+ tasarimciMin + "'," + "'" +  testerMin + "'," + "'" + yoneticiMax + "'," + "'" + analistMax 
						+ "'," + "'" + tasarimciMax + "'," + "'" + testerMax + "')";
				
				//Printing the console, for debugging purpose.
				System.out.println(sorgu);
				
				//Where server connection happens.
				MainGui.projectTableEkle(sorgu);
			}
        });
        
        btn_projeUpdate.setText("Güncelle");
        
        //Author: ÖFY
        btn_projeUpdate.addActionListener((ActionListener) new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				
				//Declerations here.
				String projectName;
				projectName = txt_ProjectName.getText();
				
				String yoneticiMin;
				yoneticiMin = txt_minManager.getText();
				String yoneticiMax;
				yoneticiMax = txt_maxManager.getText();					
				
				String analistMin;
				analistMin = txt_minAnalist.getText();
				String analistMax;
				analistMax = txt_maxAnalist.getText();
				
				String tasarimciMin;
				tasarimciMin = txt_minDesigner.getText();		
		  		String tasarimciMax;
				tasarimciMax = txt_maxDesigner.getText();
				
				String testerMin;
				testerMin = txt_minTester.getText();
				String testerMax;
				testerMax = txt_maxTester.getText();
				
				//Herein sql query's are done.
				String sql_sorgu = "UPDATE employee.projecttable SET projectName='" + projectName + "', yoneticiMin='" + yoneticiMin + "', yoneticiMax='" + yoneticiMax + 
						"', analistMin='" + analistMin + 
						"', analistMax='" + analistMax + "', tasarimciMin='" + tasarimciMin + "', tasarimciMax='" + tasarimciMax 
						+ "', testerMin='" + testerMin + "', testerMax='" + testerMax + "' WHERE projectName= '" + projectName + "'";
				
				//Printing the console, for debugging purpose.
				System.out.println(sql_sorgu);
				
				//Where server connection happens.
				MainGui.updateProjectTable(sql_sorgu);
			}
        });
        
        btn_ProjeBitir.setText("Proje Bitir");

        btn_projePersonelGoruntule.setText("Projedeki Personelleri Görüntüle");

        showProjects.setText("Projeleri Göster");
        //Author: ÖFY
        //This method shows the datas taken from employee.projecttable table.
        showProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProjectsActionPerformed(evt);
                Connection myConn;
				try {
					myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/employee", "seolargo", "123456");
					java.sql.PreparedStatement ps = myConn.prepareStatement("select * from employee.projecttable");
					ResultSet rs = ps.executeQuery();
					DefaultTableModel tm = (DefaultTableModel)jTable2.getModel();
					tm.setRowCount(0);				
					while(rs.next())
					{
						Object o[] = {rs.getString("projectName"), rs.getInt("yoneticiMin"), rs.getInt("analistMin"), 
								rs.getInt("tasarimciMin"), rs.getInt("testerMin"), rs.getInt("yoneticiMax"),
								rs.getInt("analistMax"), rs.getInt("tasarimciMax"), rs.getInt("testerMax")};
						tm.addRow(o);
					}
					
				} catch (SQLException e1) {
					e1.printStackTrace();
				}               
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txt_minAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(txt_maxAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txt_minDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(txt_maxDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(txt_minTester, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txt_maxTester, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(txt_minProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txt_maxProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(129, 129, 129)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_ProjeBitir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_projeUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(btn_projeEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(btn_projePersonelGoruntule, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(showProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_minManager, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_projeBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel13)
                    .addComponent(txt_maxManager, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_projeFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_minManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_projeBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_projeFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(showProjects)
                                .addGap(18, 18, 18)
                                .addComponent(btn_projeEkle)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ProjeBitir)
                                .addGap(18, 18, 18)
                                .addComponent(btn_projeUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btn_projePersonelGoruntule)
                                .addGap(63, 63, 63))))))
        );

        jTabbedPane1.addTab("Projects", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About Us", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>                        

    private void btn_showPersonelActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        
    }                                                

    private void showProjectsActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_ProjeBitir;
    private javax.swing.JButton btn_addPersonel;
    private javax.swing.JButton btn_projeEkle;
    private javax.swing.JButton btn_projePersonelGoruntule;
    private javax.swing.JButton btn_projeUpdate;
    private javax.swing.JButton btn_showPersonel;
    private javax.swing.JButton btn_updatePersonel;
    private javax.swing.JComboBox<String> cb_salaryType;
    private javax.swing.JComboBox<String> cb_title;
    private javax.swing.JLabel jLabel1; 
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton showProjects;
    private javax.swing.JTextField txt_BeginDate;
    private javax.swing.JTextField txt_ProjectName;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_finishDate;
    private javax.swing.JTextField txt_maxAnalist;
    private javax.swing.JTextField txt_maxDesigner;
    private javax.swing.JTextField txt_maxManager;
    private javax.swing.JTextField txt_maxProgrammer;
    private javax.swing.JTextField txt_maxTester;
    private javax.swing.JTextField txt_minAnalist;
    private javax.swing.JTextField txt_minDesigner;
    private javax.swing.JTextField txt_minManager;
    private javax.swing.JTextField txt_minProgrammer;
    private javax.swing.JTextField txt_minTester;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_projeBegin;
    private javax.swing.JTextField txt_projeFinish;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tc;
    // End of variables declaration                   
}
